### PR TITLE
Add some of the new political entities

### PR DESCRIPTION
**Pull request by aplaice**
I've chosen one commit (or more) per country for ease of inspection.  I'll squash before merging.

The maps are "under the fold" at the bottom!

<hr/>

### Wallis and Futuna

Used [SNL](https://snl.no/Wallis_og_Futuna) for Norwegian name of territory. (The brochure didn't have a corresponding entry.)

### Akrotiri and Dhekelia

<details>
<summary>For reproducibility script for adjusting colours</summary>

``` bash
curl https://upload.wikimedia.org/wikipedia/commons/c/ca/Akrotiri_and_Dhekelia_in_United_Kingdom.svg | 
    sed -e 's/fill="#E0E0E0"/fill="#FDFBE5"/' -e 's/fill="#FDFCEA"/fill="#FDFBE5"/' | inkscape -w 500 --export-png=src/media/ug-map-akrotiri_and_dhekelia.png /dev/stdin
optipng src/media/ug-map-akrotiri_and_dhekelia.png

```
</details>

Neither the brochure nor SNL had a dedicated entry, so I used Norwegian Wikipedia.

Country info duplicated from Falkland Islands, other than the Norwegian which wasn't applicable, and hence just used the generic:

> Britisk oversjøisk territorium.

("British overseas territory".)

#### Country info (provisional)
    
1.  English taken from the infobox:

    > Unincorporated internal area of Norway.

2.  German based on German equivalent of "Unincorporated area" (dropping "internal") https://de.wikipedia.org/wiki/Gemeindefreies_Gebiet#Norwegen

    > Gemeindefreies Gebiet von Norwegen.

    (The German article didn't have an appropriate description in the infobox nor (AFAICT) in the main text.)

    or perhaps alternatively:

    > Norwegisch Überseegebiet.

    (but is it really "overseas" (it is technically across the Norwegian sea)?)

3.  Spanish adapted from the infobox:

    > Territorio dependiente de Noruega.

    (Obviously this is different from the English version.)

    Possibly could just use the generic:

    > Territorio (de ultramar ?) de Noruega.

4.  French adapted from status in the infobox:

    > Territoire sous souveraineté norvégienne.

    (Obviously again different from English.)

    Possibly could instead just use the generic:

    > Territoire norvégienne (d'outre-mer ?).

5.  Norwegian adapted from Falkland islands:

    > Norsk øygruppe.

    (It's also how the Norwegian Wikipedia article describes them.)

#### Alternative names
    
I haven't mentioned Spit(s|z)bergen as an alternative name (for English, French and Spanish) since the relevant articles say that it was called that until 1925, not that it's a current alternative name for the territory.

Similarly, I haven't mentioned Svalbard as an alternative (for German) since the German article says that it's not actually used (they stick with the old pre-1925 name).

However, I'm not quite sure whether this is the right decision.

#### Alternative map

I zoomed out slightly to give more context.

<details>
<summary>Script for zooming out for reproducibility</summary>

(I obviously didn't obtain the paramters by playing around with sed, but it provides a compact way of representing the changes. (A diff/patch would be longer.))

``` bash
curl https://upload.wikimedia.org/wikipedia/commons/3/38/Svalbard_in_its_region.svg |
sed -e 's/g i:extraneous="self"/& transform="scale(0.75) translate(85, 0)"/' -e 's/g id="Mini_Map"/& transform="translate(-85, 0) scale(1.333)"/' -e 's;rect x="63.524".*;rect x="59.988" y="182.985" opacity="0.1" fill="#C02637" width="26.33" height="14.81"/>;' -e 's;rect x="63.764".*;rect x="59.988" y="182.985" fill="none" stroke="#C02637" width="26.33" height="14.81"/>;' |
inkscape -w 500 --export-png=src/media/ug-map-svalbard.png /dev/stdin
optipng src/media/ug-map-svalbard.png 
 ```
</details>

#### Country info
    
Chosen to be "State of the United States." and the equivalents (which were readily found — though obviously corrections still welcome!)

#### Alternative map

I zoomed out slightly to give more context.

<details>
<summary>Script for zooming out for reproducibility</summary>

(I obviously didn't obtain the paramters by playing around with sed, but it provides a compact way of representing the changes. (A diff/patch would be longer.))
    
``` bash
# x="364.04" y="1155.405" opacity="0.2" fill="#C12A3A" enable-background="new    " width="190.679" height="107.255"
# x="324.415" y="1143.25" opacity="0.2" fill="#C12A3A" enable-background="new    " width="251.31499999999997" height="145.135"/>
curl https://upload.wikimedia.org/wikipedia/commons/e/e5/Hawaii_in_its_region_%28special_marker%29.svg |
sed -e 's/g i:extraneous="self"/& transform="scale(0.8) translate(480, 300)"/' -e 's/g id="Mini_Map_1_"/& transform="translate(-480, -300) scale(1.25)"/' -e '/<rect/ { s/364.04/324.415/; s/1155.405/1143.25/; s/190.679/251.315/; s/107.255/145.135/; }' |
inkscape -w 500 --export-png=src/media/ug-map-hawaii.png /dev/stdin
optipng src/media/ug-map-hawaii.png
```
</details>

### Bougainville

I used the shorter "Bougainville" instead of the longer "Autonomous Region of Bougainville" ([Bougainville](https://en.wikipedia.org/wiki/Bougainville) also, among other things, refers to the island of Bougainville which is the main component of the region). (I'm interpreting "parenthetical" in our Contributing guidelines in the slightly wider meaning, i.e. not purely "surrounded by parenthesis".)

I'm not quite happy about the map, since it'd benefit from a zoom-box.  However since I think that it's borderline acceptable and adding a zoom-box would take even more playing around with maps, I'm leaving it as-is, if you agree that it's (just-about) acceptable.

<hr/>

Edit, since I forgot:

<details>
<summary>New maps</summary>

### ug-map-svalbard.png

original (as was on Wikipedia):

original

zoomed out:

zoomed out

### ug-map-hawaii.png

original:

original

zoomed out:
zoomed out

### ug-map-bougainville.png

</details>

### CODE REVIEW

**Comment by axelboc** [comment]
The maps are perfect. Thanks for adjusting the zoom levels!

I also agree with your decisions regarding country names and info. I only see one minor issue in the French country info of Bougainville: I would remove the article `la` before "Papouasie-Nouvelle-Guinée".

> I used the shorter "Bougainville" instead of the longer "Autonomous Region of Bougainville" (Bougainville also, among other things, refers to the island of Bougainville which is the main component of the region). (I'm interpreting "parenthetical" in our Contributing guidelines in the slightly wider meaning, i.e. not purely "surrounded by parenthesis".)

Off the top of my head, it's the same situation as for Zanzibar, Guernsey, and the now-defunct Saint Helena and Easter Island. Perhaps we could add something in the guidelines about choosing the short name when it's the same as territory's main island?

---

Thank you so much for this! 🎉

**Comment by aplaice** [comment]
Thanks for the feedback!

> Off the top of my head, it's the same situation as for Zanzibar, Guernsey, and the now-defunct Saint Helena and Easter Island. Perhaps we could add something in the guidelines about choosing the short name when it's the same as the territory's main island?

There are, however, also cases like [Yaren](https://en.wikipedia.org/wiki/Yaren_District) where "District" is removed from the name, (it's actually what I relied on as "precedent", as I forgot about Guernsey etc.). It is covered by a more "liberal" reading of the general rule about parenthetical portions, but obviously not by the more specific rule about islands/territories, so I'm not sure whether explicitly adding the latter would be useful. Perhaps we could mention one of the territory/island cases as an example of the general rule, though?

**Comment by axelboc** [comment]
Awesome stuff, thanks! 🚀

**Comment by aplaice** [comment]
Oops, I had forgotten to squash when I had finished!

**Comment by axelboc** [comment]
Oh no worries, it's actually nice to see each new entity as a commit. 💯

**Pull request merged**
