### PR TITLE
Add more flag similarities

### LINKED ISSUE #50: Add more flag similarity info
From a comment on the [shared deck's page](https://ankiweb.net/shared/info/2109889812):

> [...] Countries with similar flags were a lot of trouble (ex. New Zealand/Australia, Curaçao/Nauru, Palestine/Sudan, Andorra/Moldova), [...]

### PR DESCRIPTION
**Pull request by axelboc**
Fixes #50.

I've just copied your changes for now, @ohare93 (cf. https://github.com/axelboc/anki-ultimate-geography/issues/50#issuecomment-520592389). I'll take a look at them and try to add German translations asap.

### CODE REVIEW

**Comment by ohare93** [comment]
Perfect, thanks for fixing my silly blunder 👍

**Comment by aplaice** [comment]
These look useful!

Might it be worth adding a comment regarding the width of the wide band, like:

    Tajikistan (emblem, wider white band)

and

    Hungary (no emblem, narrower white band)

to the Hungary, Tajikistan pair?

**Comment by ohare93** [comment]
@aplaice I was considering that, but then I got confused by the term "band" and if it related to horizontal or veritical lines (or both!) 😅 Couldn't find the right wording myself.

**Comment by aplaice** [comment]
FWIW "band" is already used for the [Latvia-Austria pair](https://github.com/axelboc/anki-ultimate-geography/blob/c72149db892d11b267762b45c7f9add4629d4040/src/data.csv#L15), in exactly this context, so at least there's precedent for the wording. :)

**Comment by axelboc** [comment]
I've made some of the similarities more precise (e.g. "colours flipped", "other emblem" and the like), and I've added similarities for Norway/Iceland/Faroe Islands.

As discussed in #50, I've also removed the similarities that I don't believe apply to _Flag - Country_ template, for which the _Flag similarities_ field was designed. Hopefully, this should close #50.

I've also removed a few non-breakable spaces (`&nbsp;`) that had crept into a few fields.

**Comment by axelboc** [comment]
Actions for my own reference:

- [ ] Document guidelines and rules (with updates from audit)
- [ ] Remove similarities for Costa Rica / Thailand
- [ ] Remove similarities for Jordan
- [ ] Add similarities for Ghana / Bolivia
- [ ] Add similarities for Liberia / Malaysia
- [ ] Add similarities for Andorra / Romania/Chad

**Pull request merged**
