### PR TITLE
Add zoomboxes for disambiguation

### LINKED ISSUE #314: Disambiguate Macau & Hong Kong Maps
https://github.com/axelboc/anki-ultimate-geography/blob/v3.3.1/src/media/ug-map-macau.png
https://github.com/axelboc/anki-ultimate-geography/blob/v3.3.1/src/media/ug-map-hong_kong.png

These maps look almost the same.

### LINKED ISSUE #344: Add zoom boxes to Guernsey and Jersey
The maps are so similar that it's difficult to tell which is which, especially when studying on mobile.

Jersey

Guernsey

### PR DESCRIPTION
**Pull request by aplaice**
Disambiguate Hong Kong and Macau, Guernsey and Jersey, Mayotte and
Comoros.

Fix #314, fix #344.

<details><summary>Maps before and after</summary>

## Hong Kong

before

before

## Macau

before

before

## Guernsey

before

before

## Jersey

before

before

## Mayotte

before

before

## Comoros

before

before

</details>

As usual, if the maps are OK, I'll upstream to Wikimedia and update `sources.csv`.

(Note that for Guernsey, in the zoombox I selected all the islands making up the [Bailiwick of Guernsey](https://en.wikipedia.org/wiki/Bailiwick_of_Guernsey), not just the island (or the jurisdiction) of [Guernsey](https://en.wikipedia.org/wiki/Guernsey). (See also #241, which in-itself is no longer relevant due to the removal of the flags of small dependent territories, but which dealt with virtually the same issue.) I think that the issue is now more clear-cut since it's the Bailiwick which is a `Crown Dependency`, as stated in the `Country info`, not the Juridiction which is a sub-unit of the Bailiwick.)

### CODE REVIEW

**Comment by axelboc** [comment]
Love your work!! 😍 

If I really had to nitpick, perhaps the zoom boxes of Macau, Hong Kong, Comoros, and Mayotte are a tiny bit too zoomed in... but it's really insignificant, so feel free to upload as is.

**Comment by aplaice** [comment]
The zoomed-in maps that I'm relying on for these four zoom boxes don't have much more context, so it'd be relatively hard to zoom out. Hence, if it's not that much of an issue, I'll leave them as they are!

**Comment by axelboc** [comment]
Fair enough, sounds good 👍

**Comment by axelboc** [comment]
Woops, sorry, forgot to merge this one.

**Pull request merged**
