### PR TITLE
Improve night mode glow/shadow of flags

### PR DESCRIPTION
**Pull request by aplaice**
Implement @ukanuk's suggestions, resolving the problem with the glow's asymmetry, and its unnecessary visibility on a grey background.

I'm making the PR to get one step closer to fixing this, but @ukanuk, @axelboc and anyone else please feel free to tear it apart.

### CODE REVIEW

**Comment by aplaice** [comment]
I feel rather bad that I hadn't thought of these changes before @ukanuk suggested them, and that they weren't included in the released version of the deck. (The asymmetry was/is a matter of taste that simply didn't bother me (though I now agree that unlike for a shadow, it doesn't really make sense), but I had been concerned by the unnecessary glow-on-grey...)

**Comment by ukanuk** [comment]
I feel it's mostly my fault, as I was only subscribed to notifications for releases, and didn't happen to check the project for the few days right before the release, during which there was a flurry of changes including this one. I didn't notice the conversation until getting notified of the release, and reading the release notes, and clicking the linked issue to learn more (and updating to the release version to get all the changes and see them for myself).


Now I'm subscribed to be notified of all conversations, not just releases.

My guess is a lot more people are subscribed to notifications for just releases, and thus feedback will be much higher than normal immediately after a release. Maybe this feedback could be more quickly and cleanly integrated in the future by first releasing revisions as a beta, with a release note that feedback is especially welcomed for a two week period after which the full release will come.

Either that, or write a Github Action which can more easily allow smaller releases more often.

Just some thoughts. I think the current release process is fine, too. This is such an amazing collaborative deck already, and any ongoing work is just more icing on the top! My mind has been blown the last few months how CrowdAnki and Anki Deck Manager have enabled this significant community of anki editors to share their deck improvements. Who would have thought when starting this project that it would already been on a third major revision and have multiple releases each with a book chapter of improvements! So cool 😎

**Comment by axelboc** [comment]
A pre-release sounds like an excellent idea for next time, you're totally right.

FYI, I'll try to release v4.4 in a month. What I have in mind for v4.4, apart from the usual fixes, is to figure out issue #137 (and #221) and perhaps integrate some more map improvements.

---

Are you happy for this PR to be merged by the way? Or would you like to further discuss the idea of limiting the use of the glow to only the flags that need it?

**Comment by aplaice** [comment]
> Are you happy for this PR to be merged by the way? Or would you like to further discuss the idea of limiting the use of the glow to only the flags that need it?

Yes, definitely — you and @ukanuk convinced me that limiting it would not be useful and possibly harmful.

<hr/>

A pre-release is a great idea!

(Also, thanks @ukanuk for the words of support!)

**Comment by ukanuk** [comment]
This PR additionally fixes #290

**Pull request merged**
