### PR TITLE
Define and document sources and inclusion rules for oceans, seas, straits, channels and passages

### LINKED ISSUE #346: Inclusion rules for seas and related water bodies
As agreed in https://github.com/axelboc/anki-ultimate-geography/issues/137#issuecomment-620764010, and since discussion has started again on this topic in #137, I'm opening this issue to discuss inclusion rules for water bodies (oceans, seas, gulfs, straits, etc.) I'm leaving lakes and rivers out for now (see why down below).

Like for political entities (#306 + #312), we need to identify which types of water bodies to include, and then, for each type of entities:

1. find a source article on Wikipedia that lists them as exhaustively as possible;
2. come up with precise, practical inclusion rules to decide which ones and how many to include (with maps only this time -- no capitals and flags to worry about... 😄);
3. document the source article and inclusion rules in `CONTRIBUTING.md`.

#### Oceans

Like for continents, this one's easy: https://en.wikipedia.org/wiki/Ocean#Oceanic_divisions. Since we're not a historical deck, there's no debate that the world has five oceans and all five of them are to be included ... which they already are! They even have brand new maps #325! ✨ 

#### Marginal seas

Wikipedia's [list of seas](https://en.wikipedia.org/wiki/List_of_seas) seems like a good reference. The problem is that it lists gulfs, bays, straits, channels, etc. within the same _Marginal seas_ heading, without further categorisation. Apparently the terms sea, gulf, bay, sound, etc. are used inconsistently (as you've rightly pointed out in https://github.com/axelboc/anki-ultimate-geography/issues/137#issuecomment-650528659, @aplaice), so I don't think we'll be able to list them independently and apply different criteria to them.

The good news is that the list already excludes lakes with "Seas" in their names, like the Sea of Galilee or the Aral Sea. Also, we might be able to separate out straits, channels, passages, and so on. If that's indeed the case, then I think using the surface area as the sole inclusion criteria for the remaining seas, gulfs, etc. would work pretty well.

#### Straits, channels, passages, etc.

Same list as above. As @aplaice mentioned, straits between continents would be the easy pick. Also, since I can only see two channels, the English Channel and the [Mozambique Channel](https://en.wikipedia.org/wiki/Mozambique_Channel), I reckon we can include them as well. The remaining bodies are more debatable.

#### Lakes

I'd be inclined to leave these alone for now, for the following reasons:

- The [list of lakes](https://en.wikipedia.org/wiki/List_of_lakes) is quite massive and "in the process of an expansion or major restructuring".
- Sourcing the surface area of all of these is going to be quite challenging...
- Inclusion criteria are not obvious if some people are keen on keeping the Sea of Galilee and the Dead Sea.

#### Rivers, deltas, fjords, etc.

Since we don't have any in the deck yet, let's leave them out of the scope of this issue.

### PR DESCRIPTION
**Pull request by axelboc**
Fix #346.

Like for political entities, I've added a spreadsheet to list the water bodies and test/document the inclusion criteria. It contains three groups for now: seas, straits and channels/passages (seemed to make sense to group the last two together, as passages are closer to channels than straits in my mind). I haven't added continents and oceans to the spreadsheet since we don't need to apply any criteria to them.

Note that it might be a good idea to double check the `>= 2 states` columns for straits and channels/passages in case Wikidata returned any wrong or arguable results.

### CODE REVIEW

**Comment by axelboc** [comment]
Here are all the entities that need to be added to the deck:

| Seas | Straits | Channels and passages
|-|-|-|
| <ul><li>Andaman Sea<li>Arafura Sea<li>Baffin Bay<li>Banda Sea<li>Barents Sea<li>Beaufort Sea<li>Bering Sea<li>Bismarck Sea<li>Celebes Sea<li>Chukchi Sea<li>East China Sea<li>Great Australian Bight<li>Greenland Sea<li>Gulf of Aden<li>Gulf of Alaska<li>Gulf of Guinea<li>Gulf of Saint Lawrence<li>Ionian Sea<li>Java Sea<li>Kara Sea<li>Laccadive Sea<li>Laptev Sea<li>Molucca Sea<li>North Sea<li>Ross Sea<li>Scotia Sea<li>Sea of Okhotsk<li>Seram Sea<li>Solomon Sea<li>Sulu Sea<li>Timor Sea<li>Tyrrhenian Sea<li>Weddell Sea</ul>  | <ul><li>Bab-el-Mandeb<li>Strait of Magellan<li>Strait of Gibraltar<li>Singapore Strait<li>Strait of Dover<li>Palk Strait<li>Strait of Hormuz<li>Torres Strait<li>Strait of Malacca</ul> | <ul><li>Mozambique Channel</ul> |

And the ones that need to be removed:

- White Sea
- Denmark Strait

**Comment by aplaice** [comment]
On a cursory view (unfortunately, I currently don't have time for a thorough review, and likely won't this week), both the changes to `CONTRIBUTING.md` and the `physical-entities.xlsx` spreadsheet look great and in line with what we had discussed!

**Review by aplaice — APPROVED** [review]
I still haven't had time to properly review (i.e. double check everything in the spreadsheet), but that's not reason to delay merging even longer!

**Comment by axelboc** [comment]
Alright, merging now then! 🚀

I'll try to do a release next week.

**Pull request merged**
