### PR TITLE
Translate deck into German

### LINKED ISSUE #52: German translation
If I'd make a translation, would you include it? (German)

### PR DESCRIPTION
**Pull request by axelboc**
Thanks a lot @Lidara and @alpha-strike!! Fixes #52.

I've collected your translations and tidied the deck a bit, notably by:
- removing all HTML markup (to not interfere with the cards' CSS), 
- fixing punctuation and capitalisation,
- removing a couple of images that got added, and
- adding a few missing translations (esp. some flag similarities and capital hints).

In an attempt to keep the German deck maintainable in the long run, I've also done my best to bring back some of the latest translations closer to their original English counterparts. @alpha-strike, if you notice any mistakes in the deck that you had corrected and I have put back, please don't hesitate to open new issues. I'll open some myself in the next few days.

@Lindara, would you have time to please proof-read the deck one last time to make sure it all still makes sense?

Thanks again! Hopefully, we'll get more translations added soon.

### CODE REVIEW

**Comment by Lidara** [comment]
I assume you mean me with that tag. I am very willing to review it, but I won't be able to do so until next week. I haven't forgotten the project!

**Comment by axelboc** [comment]
No worries, no rush! Thanks a lot 👍

**Comment by axelboc** [comment]
I'm in the process of migrating the deck to [Anki Deck Manager](https://github.com/OnkelTem/anki-dm) - #63, which will make adding and maintaining translations much simpler. I'm closing this PR, but I'll keep the branch open so I can grab the translations from it and put them into the new CSV format at some point. I'll open a new issue to keep track of this work.

**Comment by OnkelTem** [comment]
@Lidara It should be now really easy to translate. If you didn't follow this migration here is a simple how-to:

1) Open `src/data.csv` in a spreadsheet application.
2) Add a new column and give it a name: `<Original column>:de`, where Original colum is the name of the column you want to translate. E.g. for translating country names just use: `Country:de`. For more information check out: https://github.com/OnkelTem/anki-dm#data-translation
3) Populate this colum with translations.
4) Export the file back to `data.csv`.

**Comment by axelboc** [comment]
@OnkelTem I'm going to import the German JSON deck in this branch with anki-dm and copy the columns into `data.csv`. I'll re-open a PR once I'm done ;)

**Pull request closed without merging**
