### PR TITLE
Rename Macedonia to North Macedonia

### PR DESCRIPTION
**Pull request by toblu302**
Now that the name has officially changed, it's time to update this deck.

https://vlada.mk/node/16763?ln=en-gb
https://twitter.com/Dimitrov_Nikola/status/1095381648844169217

### CODE REVIEW

**Comment by axelboc** [comment]
Great, thanks! Would you mind adding "Formerly known as Macedonia." in the _Country info_ field, please? I believe the German translation would be "Früher bekannt als Mazedonien.", @Erim24 ?

**Comment by toblu302** [comment]
Added!

**Comment by Erim24** [comment]
@axelboc Exactly. And the new name would be Nordmazedonien.
Sorry for the late reply. I somehow missed the topic here...

**Comment by axelboc** [comment]
No worries, thanks for confirming!

**Pull request merged**
