### PR TITLE
Add capital info for Canary Islands

### LINKED ISSUE #226: Add capital info for Canary Islands
See https://github.com/axelboc/anki-ultimate-geography/issues/205#issuecomment-601470159

> The capital is shared between the two cities of Santa Cruz de Tenerife and Las Palmas

### PR DESCRIPTION
**Pull request by josealberto4444**
Fixes #226 and a typo.

Edit: maybe we should wait until we get a reply in #229 and #230.

### CODE REVIEW

**Comment by axelboc** [comment]
Little typo in French: `partagée` should be `partagé`.

Also, now that I read it again, I think `entre les deux villes de` can be simplified to `entre les villes de`. It's clear that there are two cities. (A bit like when we had both "Formerly" and a date in the past in the capital info of  Kazakhstan.)

**Comment by axelboc** [comment]
No need to worry about waiting for the translations. We can fix them later on. I'll hold off publishing a version 3.3 of the deck, though.

**Comment by aplaice** [comment]
In the German, I think we can skip the "(Autonomen Gemeinschaft der)" part.

 (I had intended it to be an optional part, which I wasn't sure whether to include ("Autonomous Community of"), though didn't really make it clear — sorry!)

**Comment by Erim24** [comment]
> In the German, I think we can skip the "(Autonomen Gemeinschaft der)" part.
> 
> (I had intended it to be an optional part, which I wasn't sure whether to include ("Autonomous Community of"), though didn't really make it clear — sorry!)

I was thinking about your comment about skipping the "(Autonomen Gemeinschaft der)" and I think it's good to keep it. Having it in there keeps it clear that it is not a sovereign country (at least I wasn't sure about that anymore). Having it there doesn't really tell that it isn't a sovereign country, but it is a remainder that there "was something"

**Comment by axelboc** [comment]
FYI, I figured out why I couldn't force push, I was using git with a different account on my machine... I'll quickly fix the French translation, rebase and then merge. Thanks @josealberto4444!

**Comment by axelboc** [comment]
Oh and I've removed the parens around `Autonomen Gemeinschaft der`. 👍

**Comment by axelboc** [comment]
Arf, I missed the typo that @Erim24 had identified in #229. I've just pushed a fix to master.

**Pull request merged**
