### PR TITLE
Remove Tokelau's capital and update country info

### LINKED ISSUE #100: Capital of Tokelau?
The deck currently lists the capital of Tokelau as Atafu, but [Wikipedia lists the capital as Nukunonu](https://en.wikipedia.org/wiki/Tokelau), with a footnote that, "Each atoll has its own administrative centre." Wikipedia also says the capital rotates yearly between the three atolls that make up Tokelau, but the page that Wikipedia cites doesn't seem to support that claim. In fact, the [CIA World Factbook](https://www.cia.gov/library/publications/the-world-factbook/fields/312.html#TL) says, "the meeting place of the Tokelau Council rotates annually among the three atolls; this tradition has given rise to the somewhat misleading description that the capital rotates yearly between the three atolls; in actuality, it is the seat of the government councilors that rotates since Tokelau has no capital".

Thoughts on how to best incorporate this information into the deck? I suggest changing the `Capital` field to be `"(no capital)"`, and `Capital info` to `"There is no capital; the meeting place of the Tokelau Council rotates annually among the three atolls that make up Tokelau."`

See #20 for related discussion.

### PR DESCRIPTION
**Pull request by JohnHBrock**
Fixes #100.

I removed the capital entry for both the default language and German, but someone who knows German would need to update the `:de` country info.

### CODE REVIEW

**Comment by axelboc** [comment]
@Erim24, we need your help with a translation please 😊

> Tokelau has no official capital; the meeting place of the Tokelau Council rotates annually.

**Comment by JohnHBrock** [comment]
Done.

**Comment by Erim24** [comment]
> @Erim24, we need your help with a translation please blush
> 
> > Tokelau has no official capital; the meeting place of the Tokelau Council rotates annually.

Gosh, I'm so sorry for missing that...
However the machine translation sounds good. I'm not entirely sure about the term the translation of "Council" with "Rates". It is the proper translation but I couldn't find anything if it is the official german term. So I assume that's fine

**Comment by axelboc** [comment]
No worries! I figured we could fix it later anyway ;)

Glad to hear it's fine, though. Thanks for checking.

**Pull request merged**
