### PR TITLE
Content updates x4

### PR DESCRIPTION
**Pull request by axelboc**
Resolving four issues:

- #166 Capital of Kiribati (EN)
- #168 Change capitalisation of eSwatini to Eswatini (EN)
- #169 Greenland and the Faroe Islands are constituent countries (EN, DE, NB)
- #170 German capital of San Marino should be Stadt San Marino (DE)

For #169, I've tried to update the German and Norwegian translations. @Erim24 and @Vages, please let me know what they're worth.

### CODE REVIEW

**Comment by aplaice** [comment]
Sorry for getting around to looking at this only now, but I'm not sure about the German version of the Country info for Greenland and Faroe Islands. (Note that my German is pretty poor, so take with a grain of salt.)

Firstly, I'm 95 % sure that grammatically, it should be "Landesteil des Königreich**s** Dänemark" (the genitive of "Königreich").

Secondly, (though here I'm getting into even more uncertain territory) I have doubts whether "Landesteil" is the most accurate, German term for Greenland and the Faroe Islands. (To the extent that I can tell, I don't think that it's strictly wrong, and probably not worse than what it replaced, but possibly not the way a German would describe them.)

Landesteil is indeed what is used to describe the given entity in the German articles for [Wales](https://de.wikipedia.org/wiki/Wales) or [Scotland](https://de.wikipedia.org/wiki/Schottland). However, in the German articles for [Greenland](https://de.wikipedia.org/wiki/Gr%C3%B6nland) and [the Faroe Islands](https://de.wikipedia.org/wiki/F%C3%A4r%C3%B6er) the term isn't used at all. In the lead section, Greenland is introduced as "ein autonomer Bestandteil des Königreichs Dänemark". The Faroe Islanders are described as "eine „gleichberechtigte Nation“ innerhalb des Königreichs Dänemark" (just like the Greenlanders).

In the navigation box, at the bottom of both articles, the Faroe Islands and Greenlands are categorised as "Autonome Bestandteile der Reichsgemeinschaft des Königreichs Dänemark" (in the plural).

Hence, in the absence of recommendations from an actual native speaker, and following Wikipedia, I'd suggest using "Autonomer Bestandteil der Reichsgemeinschaft des Königreichs Dänemark", possibly skipping the (der Reichsgemeinschaft).

**Comment by axelboc** [comment]
Yeah, I hesitated... I think you're right. And I'm for skipping the _Reichsgemeinschaft_ part, as we don't use the term in the other languages and it's pretty obscure. Do you mind opening a PR to fix it, if you have time?

**Comment by aplaice** [comment]
Done in #185!

**Comment by Erim24** [comment]
Sorry for the long break. I think the variant with "Autonomer Bestandteil des Königreichs Dänemark" as it is done now is a good way to do it.

**Pull request merged**
