### PR TITLE
Generate Guids Again

### PR DESCRIPTION
**Pull request by ohare93**
Update to [Brain Brew 0.3.2](https://github.com/ohare93/brain-brew/pull/22) which adds a new `generate_guids_in_csv` task, as stated in #396. 

Tested and it works like a charm for me :+1:

### CODE REVIEW

**Review by aplaice — APPROVED** [review]
Looks and works great!

(Tested both removing a row of GUIDs (apart from the country name) and a column of GUIDs (apart from the header) and new ones were generated, as expected!)

Thanks so much!

**Review by axelboc — APPROVED** [review]

**Comment by axelboc** [comment]
Awesome!

**Comment by ohare93** [comment]
Oh god damn it! :facepalm: :laughing:

**Comment by ohare93** [comment]
Please see #402 :smile:

**Pull request merged**
