### PR TITLE
Added Russian language

### PR DESCRIPTION
**Pull request by estim**
Translation for Russian language

### CODE REVIEW

**Comment by aplaice** [comment]
Wow! Thanks for this!

Other than CSV quoting normalisation (which can be fixed with a `composer index` and which is irrelevant given the impending switch to [`brain-brew`](https://github.com/ohare93/brain-brew) and on a semi-cursory look, this looks great! I don't speak Russian, though, and can only just-about parse Cyrillic, so all I can say that the names look vaguely correct and the structure of the additions appears right.

However, I think that the consensus is that we'll be waiting until we switch to `brain-brew` to add any more languages\*, so merging this will probably need to wait until then. (None of your work will be wasted, since the translation will be easily transferable to the new system.)


\* otherwise the CSV will become completely unwieldy

**Comment by estim** [comment]
Cool!
Do I need to fix anything with `composer index`? Or you'll wait for the new system and everything will be parsed automatically?

**Comment by aplaice** [comment]
> Do I need to fix anything with composer index? Or you'll wait for the new system and everything will be parsed automatically?

No need, everything will be automatically parsed.

(The issue is that `anki-dm`, our current system, uses a weird, non-standard CSV quoting convention, "inherited" from PHP, while you used the most common (normal) CSV field quoting convention. The new system will be able to cope just as well with either.)

**Comment by ohare93** [comment]
I'll make an update for this PR after #364 is pulled :+1:

**Comment by ohare93** [comment]
PR created :+1: @estim just has to pull that, and this one will only differ in the Russian changes :+1: (plus I removed the sorting in the recipes, as it was annoying)

**Comment by axelboc** [comment]
@ohare93 I've given you contributor access to the repo, so you may be able to force-push to this branch, if it helps.

**Comment by ohare93** [comment]
> @ohare93 I've given you contributor access to the repo, so you may be able to force-push to this branch, if it helps.

Perhaps there are some Git tricks I am unaware of, but wouldn't I need to push to `estim:master`, the origin of this PR? 🤔 

Thanks for the Contributor status though! 😁 I am happy to fix it, it is is indeed in my power.

**Comment by axelboc** [comment]
Yes, GitHub allows exactly that. It comes up as an option when you open a PR from a fork, and it's enabled by default, so unless @estim disabled it, a force-push to `estim:master` should work. 🤞

**Comment by aplaice** [comment]
Perhaps to avoid force-pushing (which "feels" ugly and will make it harder to keep track of @estim's original translation, in case we want to cross-reference something (not that I'm doubting `BrainBrew`'s perfect accuracy! :))) the last commit could be made a "formal" merge?

**Comment by aplaice** [comment]
> Yes, GitHub allows exactly that. It comes up as an option when you open a PR from a fork, and it's enabled by default, so unless @estim disabled it, a force-push to estim:master should work. crossed_fingers

I *think* that @estim hasn't disabled it, since GitHub tells me that I can "Add more commits by pushing to the master branch on estim/anki-ultimate-geography."  However, I *think* that that can only be done via [CLI git rather than via the web interface](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork).

**Comment by ohare93** [comment]
>I think that @estim hasn't disabled it, since GitHub tells me that I can "Add more commits by pushing to the master branch on estim/anki-ultimate-geography." 

Adding commits to Estim's branch is normal tho :thinking: not "pushing to a PR". I made a PR immediately for this purpose, into Estim's master, as you commented and pushed to.

> However, I think that that can only be done via CLI git rather than via the web interface.

Sorry, I'm not seeing it! :sweat_smile: `gh pr checkout 363` results in a 'not possible to fast-forward' error.

I am happy to wait a few days for Estim to react and pull :smile: after which the last touches about the translation can be confirmed and checked in :+1:

**Comment by estim** [comment]
> I am happy to wait a few days for Estim to react and pull 😄 after which the last touches about the translation can be confirmed and checked in 👍
I'm not super familiar with Github and can't be sure that I'm doing something right / wrong. I've just seen your pull request in my master and merged it. What do I need to do now? - Make a pull request here again?

**Comment by ohare93** [comment]
@estim I hope you're still online, I literally updated the PR with the latest from Aplaice 4 mins after to merged :laughing: I opened a new PR, please pull that one, then all is well!

**Comment by ohare93** [comment]
Done! We are good to merge :grin: I don't believe any of us speak Russian, so if perhaps you could have a look over the Csvs and make sure all looks good (that nothing went wrong during our changes) that would be much appreciated :clap: 

@aplaice @axelboc anything left to do apart from that? :slightly_smiling_face:

**Comment by aplaice** [comment]
Thanks for your amazing work @ohare93 and @estim!

Ideally, the list of languages in `README.md` and `src/headers/desc.html` would be updated, but that can be done later, in one go (once we have even more languages!).

Looking at the CSV changes (with `git diff --word-diff-regex="[^[:space:],]+"`) I think that nothing has gone wrong, but it might indeed be useful if you (@estim) briefly looked over the CSVs (in `src/data/`; the last column is the Russian translation), if/when you have time (but no pressure!).

**Comment by estim** [comment]
Checked and it seems that everything is still ok!

**Comment by ohare93** [comment]
> Thanks for your amazing work @ohare93 and @estim!

:rocket: 

> Ideally, the list of languages in `README.md` and `src/headers/desc.html` would be updated, but that can be done later, in one go (once we have even more languages!).

Oh yes, good idea to do it all at the end :+1: If that's the case, we're ready to go! :clap:

As @axelboc seemed raring to go on this one, I will merge it! :grin:

**Comment by axelboc** [comment]
Thanks @ohare93, and of course thank you @estim! I've had a quick look this morning and nothing jumps out at me 👍

**Pull request merged**
