### PR TITLE
[WIP] Adding country details

### PR DESCRIPTION
**Pull request by code-hunger**
(Refer to #13.)
I started out with the Easter Islands. Not sure about the perfect additional info size, probably one of the two facts can be ommited, but I don't know which one.

Here's a list of states to which details can be added:

- [ ] Åland Islands
- [ ] Madeira
- [ ] Ceuta
- [ ] Nagorno Karabakh
- [ ] South Ossetia
- [ ] Grenada
- [ ] Cayman Islands
- [ ] Abkhazia
- [ ] Zanzibar
- [ ] São Tomé and Príncipe
- [ ] Somaliland
- [ ] Sahrawi Republic
- [ ] Réunion
- [ ] Mayotte
- [ ] Kingston - identical name for the capital of Jamaica and Norfolk
- [x] Easter Islands
- [ ] Canary Islands
- [ ] Transnistria
- [ ] Macau

### CODE REVIEW

**Comment by axelboc** [comment]
Let's keep the bit about the moai, I reckon:

> Polynesian island and special territory of Chile, famous for its 887 monumental stone statues called "moai".

**Comment by axelboc** [comment]
Oh and just avoid using HTML tags if you can, it will keep things nice and clean. 😉

**Comment by code-hunger** [comment]
Ok. I used HTML because I wanted to make the numbers smaller than the text.
Clearly it was too much for a single card, I'll clean it.

**Comment by axelboc** [comment]
Closing this as per our recent discussion in #51 and #13. I'll work on #60 asap.

**Pull request closed without merging**
